-- MySQL Script generated by MySQL Workbench
-- sáb 21 ago 2021 22:58:12 AST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory` DEFAULT CHARACTER SET utf8 ;
USE `inventory` ;

-- -----------------------------------------------------
-- Table `inventory`.`tipos_establecimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`tipos_establecimientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `establecimientos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`establecimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`establecimientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tipos_establecimientos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipos_establecimientos_id`),
  INDEX `fk_establecimientos_tipos_establecimientos1_idx` (`tipos_establecimientos_id` ASC),
  CONSTRAINT `fk_establecimientos_tipos_establecimientos1`
    FOREIGN KEY (`tipos_establecimientos_id`)
    REFERENCES `inventory`.`tipos_establecimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`rol_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`rol_empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `rol_empleados_id` INT NOT NULL,
  `establecimiento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `rol_empleados_id`, `establecimiento_id`),
  INDEX `fk_empleados_rol_empleados1_idx` (`rol_empleados_id` ASC),
  INDEX `fk_empleados_establecimientos1_idx` (`establecimiento_id` ASC),
  CONSTRAINT `fk_empleados_rol_empleados1`
    FOREIGN KEY (`rol_empleados_id`)
    REFERENCES `inventory`.`rol_empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_establecimientos1`
    FOREIGN KEY (`establecimiento_id`)
    REFERENCES `inventory`.`establecimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`productos_establecimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`productos_establecimientos` (
  `establecimientos_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`establecimientos_id`, `productos_id`),
  INDEX `fk_productos_establecimientos_establecimientos1_idx` (`establecimientos_id` ASC),
  CONSTRAINT `fk_productos_establecimientos_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `inventory`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_establecimientos_establecimientos1`
    FOREIGN KEY (`establecimientos_id`)
    REFERENCES `inventory`.`establecimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`facturas_despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`facturas_despacho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `establecimiento_despachante_id` INT NOT NULL,
  `establecimientos_receptor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `establecimiento_despachante_id`, `establecimientos_receptor_id`),
  INDEX `fk_facturas_despacho_establecimientos1_idx` (`establecimiento_despachante_id` ASC),
  INDEX `fk_facturas_despacho_establecimientos2_idx` (`establecimientos_receptor_id` ASC),
  CONSTRAINT `fk_facturas_despacho_establecimientos1`
    FOREIGN KEY (`establecimiento_despachante_id`)
    REFERENCES `inventory`.`establecimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturas_despacho_establecimientos2`
    FOREIGN KEY (`establecimientos_receptor_id`)
    REFERENCES `inventory`.`establecimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`productos_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`productos_facturas` (
  `facturas_despacho_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`facturas_despacho_id`, `productos_id`),
  INDEX `fk_productos_facturas_productos1_idx` (`productos_id` ASC),
  CONSTRAINT `fk_productos_facturas_facturas_despacho1`
    FOREIGN KEY (`facturas_despacho_id`)
    REFERENCES `inventory`.`facturas_despacho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_facturas_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `inventory`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
